### ISSUE TITLE
请问这个js适合用在手机termux里调用的anyproxy吗？

### ISSUE THREAD

**Issue by eastt107** [locbytes/FGO_AnyProxy#2]
我是用手机termux里运行anyproxy的。试了下1.3的，其他都没问题，就是战斗中选撤退，退出战斗会提示“服务器连接失败”，确定后继续跳出提示，只能重启游戏。 不知道是退出胜利模块的程序找不到服务器，还是中介文件无法创建的问题。

另外服务器可以用www.163.com这种的吗？  那些网站访问后也会返回200代码的吧

**Comment by locbytes** [comment]
1.3版加入了生成随机数作为战斗回合数的功能，需要在本地读写一个文件用于记录，如果termux里无权限读写文件的话，撤退时就会出现故障。
对于服务器，只需要设置的地址和代码里拦截的地址一致即可，方法是通过拦截请求并直接返回生成的随机数而实现的，所以只要两边设置的地址一样可以是任何地址（除了游戏本身会用到的地址）。
